/**
 * Email utility for sending documents
 * Uses mailto: link for simple email sending
 * For production, integrate with EmailJS or backend email service
 */

/**
 * Send document via email using mailto link
 * @param {string} documentText - The document content
 * @param {string} documentName - Name of the document
 * @param {string} recipientEmail - Optional pre-filled recipient email
 */
export const sendDocumentViaEmail = (documentText, documentName, recipientEmail = '') => {
    const subject = encodeURIComponent(`MindNest Legal Document: ${documentName}`);
    const body = encodeURIComponent(`Please find your generated legal document below:\n\n${documentText}\n\n---\nGenerated by MindNest Legal Document Drafter\nDISCLAIMER: This is a template document. Please consult a qualified lawyer before using this document for any legal purpose.`);

    // Create mailto link
    const mailtoLink = `mailto:${recipientEmail}?subject=${subject}&body=${body}`;

    // Open email client
    window.location.href = mailtoLink;
};

/**
 * Alternative: Send via EmailJS (requires setup)
 * Instructions:
 * 1. Sign up at https://www.emailjs.com/
 * 2. Create email service and template
 * 3. Get your Public Key, Service ID, and Template ID
 * 4. Add to .env: VITE_EMAILJS_PUBLIC_KEY, VITE_EMAILJS_SERVICE_ID, VITE_EMAILJS_TEMPLATE_ID
 */
import emailjs from '@emailjs/browser';

export const sendDocumentViaEmailJS = async (documentText, documentName, recipientEmail) => {
    const publicKey = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;
    const serviceId = import.meta.env.VITE_EMAILJS_SERVICE_ID;
    const templateId = import.meta.env.VITE_EMAILJS_TEMPLATE_ID;

    if (!publicKey || !serviceId || !templateId) {
        // Fallback to mailto if EmailJS not configured
        sendDocumentViaEmail(documentText, documentName, recipientEmail);
        return;
    }

    try {
        const templateParams = {
            to_email: recipientEmail,
            document_name: documentName,
            document_content: documentText,
            from_name: 'MindNest Legal Document Drafter'
        };

        await emailjs.send(serviceId, templateId, templateParams, publicKey);
        return { success: true, message: 'Email sent successfully!' };
    } catch (error) {
        console.error('Email sending failed:', error);
        return { success: false, message: 'Failed to send email. Please try again.' };
    }
};

/**
 * Prompt user for email and send document
 */
export const promptAndSendEmail = (documentText, documentName) => {
    const email = prompt('Enter email address to send document:');
    if (email && email.includes('@')) {
        sendDocumentViaEmail(documentText, documentName, email);
        return true;
    } else if (email) {
        alert('Please enter a valid email address');
        return false;
    }
    return false;
};
