import jsPDF from 'jspdf';

/**
 * Generate a PDF from legal document text
 * @param {string} documentText - The formatted document text
 * @param {string} filename - The filename for the PDF
 * @param {boolean} isPremium - Whether this is a premium user (affects watermark)
 */
export const generatePDF = (documentText, filename = 'document.pdf', isPremium = false) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    // Set font
    doc.setFont('helvetica');
    doc.setFontSize(11);

    // Add watermark for free tier
    if (!isPremium) {
        doc.setTextColor(200, 200, 200);
        doc.setFontSize(40);
        doc.text('DRAFT', 105, 150, { align: 'center', angle: 45 });
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);
    }

    // Split text into lines and add to PDF
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);

    const lines = doc.splitTextToSize(documentText, maxLineWidth);

    let y = margin;
    const lineHeight = 7;

    lines.forEach((line) => {
        if (y + lineHeight > pageHeight - margin) {
            doc.addPage();
            y = margin;
        }
        doc.text(line, margin, y);
        y += lineHeight;
    });

    // Add footer
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Page ${i} of ${totalPages} | Generated by MindNest`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    doc.save(filename);
};

/**
 * Generate a preview of the PDF (returns data URL for display)
 */
export const generatePDFPreview = (documentText, isPremium = false) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    doc.setFont('helvetica');
    doc.setFontSize(11);

    if (!isPremium) {
        doc.setTextColor(200, 200, 200);
        doc.setFontSize(40);
        doc.text('DRAFT', 105, 150, { align: 'center', angle: 45 });
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(11);
    }

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);

    const lines = doc.splitTextToSize(documentText, maxLineWidth);

    let y = margin;
    const lineHeight = 7;

    lines.forEach((line) => {
        if (y + lineHeight > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = margin;
        }
        doc.text(line, margin, y);
        y += lineHeight;
    });

    return doc.output('dataurlstring');
};
